# Generated by Django 4.2.6 on 2023-10-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='nominal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
